### ISSUE TITLE
Compatibility with SAP Hybris 6.3?

### ISSUE THREAD

**Issue by agentelinux** [stefanleh/hybris-base-image#14]
I want startup new project with SAP Hybris 6.3.
tks

**Comment by stefanleh** [comment]
Should work without any problems (6.1 is latest i've tested myself). I'll test it next week as im also starting a 6.3 project. BTW, in Release notes of 6.3 Hybris mentioned extended Docker support. Lets see what they've done. Maybe you wont need my base image for 6.3. Best regards, Stefan

**Comment by stefanleh** [comment]
Just tested it with 6.3 b2c_acc_plus recipe. Looks good.

**Comment by agentelinux** [comment]
Perfect.
How you tested?

**Comment by stefanleh** [comment]
Like described in the docu ...

 * Use the installer to build the recipe (ok, thats not in the docu as its up to you how to initially build your system)
 * run "ant production"
 * copy the production zips into new image
 * start a container using the image

**Comment by agentelinux** [comment]
Hi Stefan,

My zip from hybris is only one.

HYBRISCOMM6300P_0-20001553.zip

entrypoint.sh line 11 and 12

>        echo "Unzipping hybris production archives ..."
>        for z in hybrisServer*.zip; do unzip $z -d /home ; done

Will I change to 
 unzip HYBRISCOMM6300P_0-20001553.zip /home/hybris ;

make sense?
tks

**Comment by stefanleh** [comment]
Nope. You need to extract your zip, use the installer with a recipe you like, go to ``hybris/bin/platform``, run ``setantenv.bat/sh`` and then ``ant production``. Then you need to read the log output. It will tell you where to find the 4 zips my entrypoint script needs in the image. Usually thats ``hybris\temp\hybris\hybrisServer\``
