### ISSUE TITLE
Error with Hybris 5.7 image

### ISSUE THREAD

**Issue by anwarchk** [stefanleh/hybris-base-image#15]
@stefanleh Great work with the docker file

I am running into this issue and tried several ways to fix it, but can't make it work

Console output from docker :

`inflating: /home/hybris/bin/platform/tomcat/LICENSE  
  inflating: /home/hybris/bin/platform/tomcat/NOTICE  
  inflating: /home/hybris/bin/platform/tomcat/RELEASE-NOTES  
  inflating: /home/hybris/bin/platform/tomcat/RUNNING.txt  
  inflating: /home/hybris/bin/platform/tomcat/bin/InstallTomcatService.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/UninstallTomcatService.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/bootstrap.jar  
  inflating: /home/hybris/bin/platform/tomcat/bin/catalina-tasks.xml  
  inflating: /home/hybris/bin/platform/tomcat/bin/catalina.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/catalina.sh  
  inflating: /home/hybris/bin/platform/tomcat/bin/commons-daemon-native.tar.gz  
  inflating: /home/hybris/bin/platform/tomcat/bin/commons-daemon.jar  
  inflating: /home/hybris/bin/platform/tomcat/bin/debug.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/debug.sh  
  inflating: /home/hybris/bin/platform/tomcat/bin/jdk_logging.properties  
  inflating: /home/hybris/bin/platform/tomcat/bin/o.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/o.sh  
  inflating: /home/hybris/bin/platform/tomcat/bin/tomcat-juli.jar  
  inflating: /home/hybris/bin/platform/tomcat/bin/tomcat-native.tar.gz  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-aix-ppc-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-aix-ppc-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-freebsd-x86-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-freebsd-x86-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-hpux-ia-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-hpux-ia-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-hpux-parisc-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-hpux-parisc-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-390-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-390-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-armel-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-armhf-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-ppc-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-ppc-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-x86-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-linux-x86-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-macosx-universal-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-macosx-universal-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-solaris-sparc-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-solaris-sparc-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-solaris-x86-32  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-solaris-x86-64  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-windows-ia-64.exe  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-windows-x86-32.exe  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper-windows-x86-64.exe  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper.bat  
  inflating: /home/hybris/bin/platform/tomcat/bin/wrapper.sh  
  inflating: /home/hybris/bin/platform/tomcat/conf/README.txt  
  inflating: /home/hybris/bin/platform/tomcat/conf/catalina.policy  
  inflating: /home/hybris/bin/platform/tomcat/conf/catalina.properties  
  inflating: /home/hybris/bin/platform/tomcat/conf/context.xml  
  inflating: /home/hybris/bin/platform/tomcat/conf/hybris-wrapper-license.conf  
  inflating: /home/hybris/bin/platform/tomcat/conf/i3-log.conf  
  inflating: /home/hybris/bin/platform/tomcat/conf/jmxremote.access  
  inflating: /home/hybris/bin/platform/tomcat/conf/jmxremote.password  
  inflating: /home/hybris/bin/platform/tomcat/conf/server-minimal.xml  
  inflating: /home/hybris/bin/platform/tomcat/conf/web.xml  
  inflating: /home/hybris/bin/platform/tomcat/conf/wrapper-minimal.conf  
  inflating: /home/hybris/bin/platform/tomcat/lib/annotations-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/catalina-ant.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/catalina-ha.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/catalina-jmx-remote.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/catalina-tribes.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/catalina.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/ecj-4.4.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/el-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/jasper-el.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/jasper.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/jsp-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/keystore  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-aix-ppc-32.a  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-aix-ppc-64.a  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-freebsd-x86-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-freebsd-x86-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-hpux-ia-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-hpux-ia-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-hpux-parisc-32.sl  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-hpux-parisc-64.sl  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-390-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-390-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-armel-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-armhf-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-ia-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-ppc-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-ppc-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-x86-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-linux-x86-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-macosx-universal-32.jnilib  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-macosx-universal-64.jnilib  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-solaris-sparc-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-solaris-sparc-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-solaris-x86-32.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/libwrapper-solaris-x86-64.so  
  inflating: /home/hybris/bin/platform/tomcat/lib/servlet-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-coyote.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-dbcp.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-i18n-es.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-i18n-fr.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-i18n-ja.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-jdbc.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-juli-adapters.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat-util.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/tomcat7-websocket.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/websocket-api.jar  
  inflating: /home/hybris/bin/platform/tomcat/lib/wrapper-version.txt  
  inflating: /home/hybris/bin/platform/tomcat/lib/wrapper-windows-ia-64.dll  
  inflating: /home/hybris/bin/platform/tomcat/lib/wrapper-windows-x86-32.dll  
  inflating: /home/hybris/bin/platform/tomcat/lib/wrapper-windows-x86-64.dll  
  inflating: /home/hybris/bin/platform/tomcat/lib/wrapper.jar  
  inflating: /home/hybris/bin/platform/tomcat/tomcat_context.tpl  
Platform home set to : /home/hybris/bin/platform/
Running hybrisPlatform on Tomcat...
FATAL  | wrapper  | Unable to open configuration file: /home/hybris/bin/platform/tomcat/bin/../conf/wrapper.conf (No such file or directory)
FATAL  | wrapper  |   Current working directory: /home/hybris/bin/platform/tomcat/bin`

These are the files that gets added to my image:

`hybrisServer-Platform.zip
  hybrisServer-Config.zip
  hybrisServerREADME.txt
  hybrisServer-AllExtensions.zip`

And here is the command I run to get these files:

`ant production -Dproduction.legacy.mode=false -Dproduction.include.tomcat=true -Dtomcat.legacy.deployment=false`

I added some customization to your `entrypoint.sh` as follows, just to get it working. I assumed some kind of permission issue where the required directory or file is not accessible.

  `chown -R hybris /home/hybris
    chmod +x hybrisserver.sh
    chmod -R +x ${PLATFORM_HOME}/tomcat/bin
    chmod -R +x ${PLATFORM_HOME}/tomcat/conf
    chmod -R +x /home/hybris/config/tomcat/conf
    chmod +x hybrisserver.sh`

Please let me know if you have input.

Thanks
Anwar

**Comment by stefanleh** [comment]
Hi Anwar, can you please try ``ant production -Dproduction.legacy.mode=false`` ? Afaik the other options you've added are for a provided instead the bundled tomcat. Thats not yet supported by my image. Best regards, Stefan

**Comment by anwarchk** [comment]
@stefanleh I noticed that when I run `ant production`, it doesn't include the `wrapper.conf` from `$HYBRIS_HOME/platform/bin/tomcat/conf`, but it does include the file from a different location, `$HYBRIS_HOME/config/tomcat/conf/wrapper.conf`. But the `wrapper.sh` in `$HYBRIS_HOME/config/tomcat/bin/wrapper.sh` is expecting the conf file to be present relative to it's root and it can't find it there and hence it fails. 

Is this something you have seen ? 
Thanks in advance,
Anwar

**Comment by stefanleh** [comment]
Hi Anwar, i havent seen this so far. Can you please describe how exactly you create the image? If you want you can send an private email to me if you dont want to publish too much of your internals. Best regards, Stefan

**Comment by anwarchk** [comment]
@stefanleh Since the platform/bin/tomcat/conf/wrapper.conf contains user specific local machine details (JAVA_HOME, HYBRIS_HOME) etc, how do you specify a wrapper.conf when you run it on Docker ?

**Comment by stefanleh** [comment]
I've never needed to specify one. But if you want to override a specific file (wrapper.conf) you can mount it into the container when you create it or just plain copy it to the right place via your own Dockerfile. Please see docker documentation for instruction on how to achieve that.

**Comment by stefanleh** [comment]
@anwarchk I played around with 6.3 today and recognized that after initial build via installer script (installer/install.sh) i needed a ``ant clean all production`` to get things right. Maybe thats worth a try on your side as well.

**Comment by anwarchk** [comment]
@stefanleh I upgraded to 6 and everything worked as expected. It had to be something with my version 5.8. Thanks for all the inputs.
