### ISSUE TITLE
Hybris 6.3 ant initialize

### ISSUE THREAD

**Issue by finamdar** [stefanleh/hybris-base-image#19]
Hi @stefanleh,

I am facing the following issue on starting the container with environment variable $HYBRIS_INITIALIZE_SYSTEM = yes in the docker file.
I am getting this issue when ant initialize is being executed. However, server starts successfully after this.

[BUILD FAILED
/home/hybris/bin/platform/build.xml:20: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/compiling.xml:90: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/compiling.xml:148: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/util.xml:20: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/compiling.xml:155: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/compiling.xml:297: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/util.xml:144: The following error occurred while executing this line:
/home/hybris/bin/ext-atdd/atddengine/buildcallbacks.xml:29: The following error occurred while executing this line:
/home/hybris/bin/platform/resources/ant/util.xml:91: /home/hybris/bin/ext-atdd/atddengine/src does not exist.](url)

I got the project artifacts after executing ant production -Dproduction.legacy.mode=false.
On simply running ant production to create the project artifacts I am getting the error of wrapper.conf.

Could you please let me know if you have ever observed this issue and how I could resolve this.

Thank you,
Farhan

**Comment by stefanleh** [comment]
Hi @finamdar,

i've seen this issue before and think its because this extension is not added to the artifacts.
Will check this soon.

Best regards, Stefan

**Comment by finamdar** [comment]
Hi @stefanleh,

I modified the ant initialize command to ant initialize -Dde.hybris.platform.ant.production.skip.build=true after which ant initialize was successful.

Thanks, Farhan

**Comment by stefanleh** [comment]
Tnx for the information. Would you like to submit a PR for this? I thinks its generally useful to avoid the rebuild in the container.
