### ISSUE TITLE
Hybris packaging of zips creates inclusive of hybris folder

### ISSUE THREAD

**Issue by davehewy** [stefanleh/hybris-base-image#26]
Not explicitly a problem with your code, but, an `ant production` will create zips inclusive of the hybris/ folder. When $HYBRIS_HOME is set to /home/hybris actual unzip will unpack to /home/hybris/hybris causing everything in entrypoint to fail with path errors.

**Comment by stefanleh** [comment]
Hello Dave, i understand your issue, but i would like to leave the defaults in place as after some years with hybris development i learned that the more you tweak the more you will suffer from it. But feel free to tweak the ant scripts of hybris before building the zips. I still have some hope they will make the move to Gradle someday. That would make such tweaks easier and more reliable. In current state (mixture of gradle, maven and ant) its cumbersome to deal with their build environment. Best regards, Stefan
